# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d16193a52732c6b0fd52ca4fe6dcb087fe3b2f1dd7ab11de7b89f20f4fd8a9b4c8d81e955aac25ac90bedbd2b0b46139032914e843a892cb433632058a1ed1e9

test:
  secret_key_base: 9b8f6e71d059f02c7c078938f30658bec50af57011b65c50aad3fdb083bbe45c5792d0e99556485d3a573013432d42517929df6290d461f091e14a7ec3f74b09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
